<?php
/**
 * Страница "Список расширений модулей с правами доступа".
 * 
 * Английская (британская) локализация.
 * 
 * Этот файл является частью модуля веб-приложения GearMagic.
 * 
 * @copyright Copyright (c) 2015 Веб-студия GearMagic
 * @license https://gearmagic.ru/license/
 */
?>
<article>
    <h1>List of module extensions with permissions</h1>
    <div class="g-help-screen g-help-screen--hidable">
        <img src="<?= $assetsUrl, '/help/extensionsgrid.png' ?>" />
    </div>
    <p>The list appears after clicking on the item <b>"Permissions for extensions"</b> of the context menu of the selected user role.</p>
    <h2>List columns</h2>
    <ul class="g-help-list">
        <li><b>Module name.</b> Module name;</li>
        <li><b>Extension name / Permission.</b> Name of the module extension with access rights (permissions).</li>
        <li><b>Access.</b> The flag defines access to the module extension with the specified permission.</li>
    </ul>

    <h2>Toolbar</h2>
    <ul class="g-help-list">
        <li><img class="g-help-icon" src="<?= $themeUrl, '/assets/icons/svg/basic/cleanup.svg' ?>" /> <b>Clear.</b> Revokes all permissions for all module extensions;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/assets/icons/svg/basic/refresh.svg' ?>" /> <b>Refresh.</b> Refresh the list of module extensions with access rights;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/widgets/images/grid/grid-profiling-off.svg' ?>" /> <b>Record profiling.</b> Expands or collapses the Navigation Panel to display information about the selected permission;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/assets/icons/svg/basic/help.svg' ?>" /> <b>Help.</b> Show the help window for the current list;</li>
        <li><img class="g-help-icon" src="<?= $themeUrl, '/assets/icons/svg/basic/search.svg' ?>" /> <b>Search.</b> Shows the form for searching records in the list.</li>
    </ul>
</article>