<?php
/**
 * Страница "Содержание".
 * 
 * Локализации по умолчанию.
 * 
 * Этот файл является частью модуля веб-приложения GearMagic.
 * 
 * @copyright Copyright (c) 2015 Веб-студия GearMagic
 * @license https://gearmagic.ru/license/
 */
?>
<article>
    <h1>User Roles and Permissions</h1>
    <div class="g-help-icon">
        <img src="<?= $assetsUrl, '/images/icon.svg' ?>" />
    </div>
    <p>Determining access rights for user roles to components (modules, module extensions) of a web application.</p>

    <h2>Содержание:</h2>
    <ul class="g-help-list">
        <li><a href="<?= $url('rolegrid') ?>">List of user roles</a></li>
        <li><a href="<?= $url('modulesgrid') ?>">List of modules with permissions</a></li>
        <li><a href="<?= $url('extensionsgrid') ?>">List of module extensions with permissions</a></li>
        <li><a href="<?= $url('roleform') ?>">Add / edit user role form</a></li>
    </ul>
</article>