<?php
/**
 * Страница "Содержание".
 * 
 * Русская локализации.
 * 
 * Этот файл является частью модуля веб-приложения GearMagic.
 * 
 * @copyright Copyright (c) 2015 Веб-студия GearMagic
 * @license https://gearmagic.ru/license/
 */
?>
<article>
    <h1>Роли и права доступа пользователей</h1>
    <div class="g-help-icon">
        <img src="<?= $assetsUrl, '/images/icon.svg' ?>" />
    </div>
    <p>Определение прав доступа ролям пользователей к компонентам (модулям, расширениям модулей) веб-приложения.</p>

    <h2>Содержание:</h2>
    <ul class="g-help-list">
        <li><a href="<?= $url('rolegrid') ?>">Список ролей пользователей</a></li>
        <li><a href="<?= $url('modulesgrid') ?>">Список модулей с правами доступа</a></li>
        <li><a href="<?= $url('extensionsgrid') ?>">Список расширений модулей с правами доступа</a></li>
        <li><a href="<?= $url('roleform') ?>">Форма добавления / редактирования роли пользователя</a></li>
    </ul>
</article>