<?php
/**
 * Страница "Форма добавления / редактирования роли пользователя".
 * 
 * Русская локализации.
 * 
 * Этот файл является частью модуля веб-приложения GearMagic.
 * 
 * @copyright Copyright (c) 2015 Веб-студия GearMagic
 * @license https://gearmagic.ru/license/
 */
?>
<article>
    <h1>Форма добавления / редактирования роли пользователя</h1>
    <div class="g-help-screen g-help-screen--hidable">
        <img src="<?= $assetsUrl, '/help/roleform.png' ?>" />
    </div>
    <p>Форма появляется после нажатия на кнопку <b>"Добавить"</b> панели инструментов списка пользователей или выбора пункта <b>"Редактировать"</b> контекстного меню выбранной записи.</p>
    <h2>Поля формы</h2>
    <ul class="g-help-list">
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Название роли.</b> Название роли пользователей;</li>
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Сокращенное название.</b> Сокращённое название роли пользователей;</li>
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Описание.</b> Описание роли пользователей;</li>
        <li><span class="g-help-fld g-help-fld_combo"></span> <b>Унаследован от ролей.</b> Список ролей пользователей от которых унаследована роль.</li>
    </ul>
</article>