<?php
/**
 * Страница "Форма добавления / редактирования роли пользователя".
 * 
 * Английская (британская) локализация.
 * 
 * Этот файл является частью модуля веб-приложения GearMagic.
 * 
 * @copyright Copyright (c) 2015 Веб-студия GearMagic
 * @license https://gearmagic.ru/license/
 */
?>
<article>
    <h1>Add / edit user role form</h1>
    <div class="g-help-screen g-help-screen--hidable">
        <img src="<?= $assetsUrl, '/help/roleform.png' ?>" />
    </div>
    <p>The form appears after clicking the <b>"Add"</b> button on the user list toolbar or selecting the <b>"Edit"</b> item from the context menu of the selected record.</p>
    <h2>Form fields</h2>
    <ul class="g-help-list">
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Role name.</b> User role name;</li>
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Short name.</b> User role short name;</li>
        <li><span class="g-help-fld g-help-fld_text"></span> <b>Description.</b> User role description;</li>
        <li><span class="g-help-fld g-help-fld_combo"></span> <b>Inherited from roles.</b> List of user roles from which the role is inherited.</li>
    </ul>
</article>